version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      vitepress:
        patterns:
          - vitepress*
          - vite*
          - vue*
          - typescript

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
